default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: pokeportal_development
  username: pokeportal

test:
  <<: *default
  database: pokeportal_test
  username: pokeportal

production:
  <<: *default
  database: pokeportal_production
  username: pokeportal
  password:
